import { useState, useEffect, useRef } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { LoginModal, SignupModal } from "./AuthModals";

/* ---- Animation variants ---- */
const pageVariants = {
  initial: { opacity: 0 },
  animate: { opacity: 1, transition: { duration: 0.5 } },
  exit: { opacity: 0, transition: { duration: 0.2 } },
};

const stagger = {
  animate: { transition: { staggerChildren: 0.12 } },
};

const fadeUp = {
  initial: { opacity: 0, y: 30 },
  animate: { opacity: 1, y: 0, transition: { duration: 0.7, ease: [0.22, 1, 0.36, 1] } },
};

/* ---- Feature data ---- */
const features = [
  { icon: "🎯", title: "Tailored Just for You", desc: "Get interview questions and model answers based on your role, experience, and specific focus areas — no generic practice here.", color: "#d4940a", gradient: "linear-gradient(135deg, #f5d06b, #d4940a)" },
  { icon: "🧠", title: "Learn at Your Own Pace", desc: "Expand answers only when you're ready. Dive deeper into any concept instantly with AI-powered detailed explanations.", color: "#b8860b", gradient: "linear-gradient(135deg, #e8d18a, #b8860b)" },
  { icon: "📝", title: "Capture Your Insights", desc: "Add personal notes to any question and pin important ones to the top — making your learning more organized and impactful.", color: "#c49518", gradient: "linear-gradient(135deg, #f0d878, #c49518)" },
  { icon: "💡", title: 'Understand the "Why" Behind Answers', desc: "Beyond just answers — unlock detailed concept explanations generated by AI, helping you truly master each topic.", color: "#a87608", gradient: "linear-gradient(135deg, #e8c460, #a87608)" },
  { icon: "💾", title: "Save, Organize, and Revisit", desc: "Easily save your interview sets, organize them neatly in your dashboard, and pick up right where you left off.", color: "#d4a020", gradient: "linear-gradient(135deg, #f5d878, #d4a020)" },
];

/* ---- How It Works ---- */
const steps = [
  { num: "01", title: "Choose Your Role", desc: "Select your job title, experience level, and key topics you want to focus on.", icon: "👤" },
  { num: "02", title: "Get AI Questions", desc: "Receive tailored interview questions with model answers generated instantly.", icon: "🤖" },
  { num: "03", title: "Test & Learn", desc: "Practice with quiz mode, expand answers, and deep-dive into explanations.", icon: "📖" },
  { num: "04", title: "Ace Your Interview", desc: "Walk in confident with thorough preparation. Track progress across sessions.", icon: "🏆" },
];

/* ---- Intersection Observer hook ---- */
const useInView = (threshold = 0.2) => {
  const ref = useRef(null);
  const [inView, setInView] = useState(false);
  useEffect(() => {
    const observer = new IntersectionObserver(([entry]) => { if (entry.isIntersecting) setInView(true); }, { threshold });
    if (ref.current) observer.observe(ref.current);
    return () => observer.disconnect();
  }, [threshold]);
  return [ref, inView];
};

/* ---- Golden Decorative Background ---- */
const GoldenBackground = () => (
  <div style={{ position: "absolute", inset: 0, overflow: "hidden", pointerEvents: "none", zIndex: 0 }}>
    {/* Large radial glow */}
    <div style={{
      position: "absolute", top: "-20%", left: "50%", transform: "translateX(-50%)",
      width: "120%", height: "70%",
      background: "radial-gradient(ellipse at center, rgba(212,148,10,0.08) 0%, rgba(245,208,107,0.04) 40%, transparent 70%)",
    }} />
    {/* Decorative circles */}
    {[...Array(8)].map((_, i) => (
      <motion.div
        key={i}
        style={{
          position: "absolute",
          width: 4 + i * 6,
          height: 4 + i * 6,
          borderRadius: "50%",
          border: `1px solid rgba(212, 148, 10, ${0.06 + i * 0.01})`,
          left: `${10 + i * 12}%`,
          top: `${15 + (i % 4) * 20}%`,
        }}
        animate={{
          y: [0, -15 - i * 3, 0],
          x: [0, 8 - i * 2, 0],
          opacity: [0.3, 0.6, 0.3],
        }}
        transition={{
          duration: 5 + i * 0.8,
          repeat: Infinity,
          ease: "easeInOut",
          delay: i * 0.4,
        }}
      />
    ))}
    {/* Golden diamond shapes */}
    {[...Array(4)].map((_, i) => (
      <motion.div
        key={`d-${i}`}
        style={{
          position: "absolute",
          width: 8 + i * 3,
          height: 8 + i * 3,
          background: `rgba(212, 148, 10, ${0.05 + i * 0.01})`,
          transform: "rotate(45deg)",
          left: `${20 + i * 20}%`,
          top: `${30 + (i % 3) * 25}%`,
          borderRadius: 2,
        }}
        animate={{
          y: [0, -20, 0],
          rotate: [45, 90, 45],
          scale: [1, 1.3, 1],
        }}
        transition={{
          duration: 6 + i,
          repeat: Infinity,
          ease: "easeInOut",
          delay: i * 0.7,
        }}
      />
    ))}
  </div>
);

/* ---- Geometric Pattern Overlay ---- */
const GeoPattern = () => (
  <div style={{
    position: "absolute", inset: 0, overflow: "hidden", pointerEvents: "none", zIndex: 0, opacity: 0.35,
  }}>
    <svg style={{ position: "absolute", top: 0, right: 0, width: "40%", height: "100%" }} viewBox="0 0 400 600" fill="none">
      <circle cx="350" cy="100" r="180" stroke="rgba(212,148,10,0.08)" strokeWidth="1" fill="none" />
      <circle cx="350" cy="100" r="140" stroke="rgba(212,148,10,0.05)" strokeWidth="1" fill="none" />
      <circle cx="350" cy="100" r="100" stroke="rgba(212,148,10,0.03)" strokeWidth="1" fill="none" />
    </svg>
    <svg style={{ position: "absolute", bottom: 0, left: 0, width: "30%", height: "60%" }} viewBox="0 0 300 400" fill="none">
      <circle cx="20" cy="350" r="150" stroke="rgba(212,148,10,0.06)" strokeWidth="1" fill="none" />
      <circle cx="20" cy="350" r="110" stroke="rgba(212,148,10,0.04)" strokeWidth="1" fill="none" />
    </svg>
  </div>
);

/* ---- Star Rating Component ---- */
const StarRating = ({ count }) => (
  <div style={{ display: "flex", gap: 3 }}>
    {[...Array(count)].map((_, i) => (
      <span key={i} style={{ color: "#d4940a", fontSize: 14 }}>★</span>
    ))}
  </div>
);

const Landing = () => {
  const [modal, setModal] = useState(null);
  const [scrolled, setScrolled] = useState(false);
  const [featuresRef, featuresInView] = useInView(0.15);
  const [howRef, howInView] = useInView(0.15);
  const [activeFooterLink, setActiveFooterLink] = useState(null);

  const footerLinks = [
    {
      name: "Features",
      icon: "✦",
      desc: "Our platform offers AI-generated interview questions tailored to your role and experience level, deep-dive explanations for every concept, a quiz mode with timer for realistic practice, and organized session management to track your progress over time."
    },
    {
      name: "How It Works",
      icon: "⚡",
      desc: "Simply sign up, choose your target role and technologies, and our AI generates personalized interview questions. Expand any answer for detailed explanations, use 'Learn More' to dive deeper, and test yourself with timed quizzes to build confidence."
    },
    {
      name: "About",
      icon: "💡",
      desc: "Interview Prep AI was built by developers, for developers. We understand the stress of technical interviews and created a tool that helps you truly understand concepts — not just memorize answers. Our mission is to make quality interview preparation accessible to everyone."
    },
    {
      name: "Privacy",
      icon: "🔒",
      desc: "Your data is safe with us. We use industry-standard encryption to protect your personal information and interview data. We never share your data with third parties, and you can delete your account and all associated data at any time."
    },
    {
      name: "Terms",
      icon: "📄",
      desc: "By using Interview Prep AI, you agree to use the platform for personal interview preparation purposes. All AI-generated content is provided as educational material. We reserve the right to update these terms, and continued use constitutes acceptance of any changes."
    },
  ];


  useEffect(() => {
    const handleScroll = () => setScrolled(window.scrollY > 20);
    window.addEventListener("scroll", handleScroll);
    return () => window.removeEventListener("scroll", handleScroll);
  }, []);



  return (
    <motion.div
      variants={pageVariants}
      initial="initial"
      animate="animate"
      exit="exit"
      style={{
        fontFamily: "var(--font-sans)",
        background: "var(--bg-golden)",
        minHeight: "100vh",
        color: "var(--text)",
        position: "relative",
      }}
    >
      {/* ===== Navbar ===== */}
      <nav
        className="glass nav-container"
        style={{
          height: 68,
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
          position: "fixed",
          top: 0,
          left: 0,
          right: 0,
          zIndex: 100,
          borderBottom: scrolled ? "1px solid var(--border-golden)" : "1px solid transparent",
          boxShadow: scrolled ? "0 4px 30px rgba(212, 148, 10, 0.08)" : "none",
          transition: "all var(--transition)",
        }}
      >
        <div style={{ display: "flex", alignItems: "center", gap: 12 }}>
          <div style={{
            width: 36, height: 36, borderRadius: "var(--radius-sm)",
            background: "linear-gradient(135deg, #d4940a, #f5d06b)",
            display: "flex", alignItems: "center", justifyContent: "center",
            fontSize: 16, color: "#fff", fontWeight: 700,
            boxShadow: "0 2px 10px rgba(212,148,10,0.3)",
          }}>✦</div>
          <span style={{ fontSize: 18, fontWeight: 700, letterSpacing: "-0.5px", color: "var(--text)" }}>
            Interview Prep <span style={{ color: "var(--accent)" }}>AI</span>
          </span>
        </div>
        <div style={{ display: "flex", alignItems: "center", gap: 16 }}>
          <button
            className="nav-link-btn"
            onClick={() => document.getElementById("features")?.scrollIntoView({ behavior: "smooth" })}
            style={{
              background: "none", border: "none", color: "var(--text-secondary)",
              fontSize: 13, fontWeight: 500, cursor: "pointer", fontFamily: "inherit",
              padding: "8px 14px", borderRadius: "var(--radius-full)",
              transition: "all var(--transition-fast)",
            }}
            onMouseEnter={e => e.target.style.color = "var(--text)"}
            onMouseLeave={e => e.target.style.color = "var(--text-secondary)"}
          >Features</button>
          <button
            className="nav-link-btn"
            onClick={() => document.getElementById("how-it-works")?.scrollIntoView({ behavior: "smooth" })}
            style={{
              background: "none", border: "none", color: "var(--text-secondary)",
              fontSize: 13, fontWeight: 500, cursor: "pointer", fontFamily: "inherit",
              padding: "8px 14px", borderRadius: "var(--radius-full)",
              transition: "all var(--transition-fast)",
            }}
            onMouseEnter={e => e.target.style.color = "var(--text)"}
            onMouseLeave={e => e.target.style.color = "var(--text-secondary)"}
          >How It Works</button>
          <button
            id="nav-login-btn"
            className="nav-login-btn"
            onClick={() => setModal("login")}
            style={{
              background: "linear-gradient(135deg, #d4940a, #b8860b)",
              color: "#fff", border: "none",
              padding: "10px 28px", borderRadius: "var(--radius-full)",
              fontSize: 13, fontWeight: 600, cursor: "pointer", fontFamily: "inherit",
              transition: "all var(--transition-fast)",
              boxShadow: "0 4px 15px rgba(212,148,10,0.3)",
              letterSpacing: "0.3px",
            }}
            onMouseEnter={e => { e.target.style.transform = "translateY(-1px)"; e.target.style.boxShadow = "0 6px 20px rgba(212,148,10,0.4)"; }}
            onMouseLeave={e => { e.target.style.transform = "translateY(0)"; e.target.style.boxShadow = "0 4px 15px rgba(212,148,10,0.3)"; }}
          >
            Login / Sign Up
          </button>
        </div>
      </nav>

      {/* ===== Hero + App Preview Combined Section ===== */}
      <style>{`
        .nav-container {
          padding: 0 60px;
        }
        @media (max-width: 768px) {
          .nav-container {
            padding: 0 16px !important;
          }
          .nav-link-btn {
            display: none !important;
          }
          .nav-login-btn {
            padding: 8px 16px !important;
            font-size: 12px !important;
          }
        }
        .hero-combined {
          display: grid;
          grid-template-columns: 1fr 1fr;
          gap: 48px;
          align-items: center;
        }
        @media (max-width: 900px) {
          .hero-combined {
            grid-template-columns: 1fr !important;
            gap: 40px;
          }
          .hero-left { text-align: center !important; }
          .hero-left .hero-cta { justify-content: center !important; }
          .hero-preview-inner {
            grid-template-columns: 1fr !important;
          }
          .hero-preview-side { display: none; }
        }
        @media (max-width: 600px) {
          .hero-combined { gap: 32px; }
        }
      `}</style>
      <section style={{
        position: "relative",
        maxWidth: 1200, margin: "0 auto", padding: "140px 40px 80px",
      }}>
        <GoldenBackground />
        <GeoPattern />

        <div className="hero-combined" style={{ position: "relative", zIndex: 1 }}>
          {/* LEFT: Hero Content */}
          <motion.div
            className="hero-left"
            variants={stagger} initial="initial" animate="animate"
            style={{ textAlign: "left" }}
          >
            {/* Premium Badge */}
            <motion.div variants={fadeUp}>
              <motion.div
                animate={{ y: [0, -6, 0] }}
                transition={{ duration: 3, repeat: Infinity, ease: "easeInOut" }}
                style={{
                  display: "inline-flex", alignItems: "center", gap: 8,
                  background: "linear-gradient(135deg, rgba(212,148,10,0.08), rgba(245,208,107,0.12))",
                  border: "1px solid rgba(212,148,10,0.2)",
                  borderRadius: "var(--radius-full)", padding: "10px 22px", marginBottom: 28,
                  backdropFilter: "blur(10px)",
                }}
              >
                <span style={{
                  width: 6, height: 6, borderRadius: "50%",
                  background: "var(--accent)", boxShadow: "0 0 8px var(--accent-glow)",
                  animation: "breathe 2s ease-in-out infinite",
                }} />
                <span style={{ fontSize: 13, fontWeight: 600, color: "var(--accent)", letterSpacing: "0.5px" }}>
                  AI-Powered Interview Preparation
                </span>
              </motion.div>
            </motion.div>

            {/* Heading */}
            <motion.h1
              variants={fadeUp}
              style={{
                fontFamily: "var(--font-serif)", fontSize: "clamp(32px, 4vw, 56px)",
                lineHeight: 1.1, marginBottom: 22, letterSpacing: "-1.5px",
                fontWeight: 400,
              }}
            >
              Ace Interviews with{" "}
              <span className="gradient-text" style={{ fontStyle: "italic" }}>AI-Powered</span>
              <br />
              Learning
            </motion.h1>

            {/* Subtitle */}
            <motion.p
              variants={fadeUp}
              style={{
                fontSize: "clamp(14px, 1.2vw, 17px)", lineHeight: 1.8,
                color: "var(--text-secondary)", maxWidth: 480, marginBottom: 36,
                fontWeight: 400,
              }}
            >
              Get role-specific questions, expand answers when you need them, dive deeper into concepts,
              and organize everything your way. From preparation to mastery.
            </motion.p>

            {/* CTA Buttons */}
            <motion.div className="hero-cta" variants={fadeUp} style={{ display: "flex", gap: 14, flexWrap: "wrap" }}>
              <motion.button
                id="hero-get-started"
                onClick={() => setModal("signup")}
                whileHover={{ y: -3, boxShadow: "0 12px 40px rgba(212,148,10,0.45)" }}
                whileTap={{ scale: 0.98 }}
                className="golden-shine"
                style={{
                  background: "linear-gradient(135deg, #d4940a, #b8860b)",
                  color: "#fff", border: "none", padding: "14px 34px",
                  borderRadius: "var(--radius-full)", fontSize: 14, fontWeight: 600,
                  cursor: "pointer", fontFamily: "inherit",
                  boxShadow: "0 8px 30px rgba(212,148,10,0.35)",
                  transition: "all var(--transition)",
                  display: "flex", alignItems: "center", gap: 10,
                  letterSpacing: "0.3px",
                }}
              >
                Get Started<span style={{ fontSize: 16 }}>→</span>
              </motion.button>

              <motion.button
                id="hero-learn-more"
                onClick={() => document.getElementById("features")?.scrollIntoView({ behavior: "smooth" })}
                whileHover={{ y: -3, background: "rgba(212,148,10,0.06)" }}
                whileTap={{ scale: 0.98 }}
                style={{
                  background: "transparent", color: "var(--text)",
                  border: "1px solid var(--border-golden)", padding: "14px 30px",
                  borderRadius: "var(--radius-full)", fontSize: 14, fontWeight: 600,
                  cursor: "pointer", fontFamily: "inherit", transition: "all var(--transition)",
                }}
              >
                Learn More
              </motion.button>
            </motion.div>
          </motion.div>

          {/* RIGHT: App Preview */}
          <motion.div
            initial={{ opacity: 0, x: 40 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.8, delay: 0.3, ease: [0.22, 1, 0.36, 1] }}
          >
            <div
              style={{
                background: "var(--bg-card)", borderRadius: "var(--radius-2xl)",
                border: "1px solid var(--border)", overflow: "hidden",
                boxShadow: "0 30px 80px rgba(160,130,60,0.12), 0 0 0 1px rgba(212,148,10,0.05)",
                backdropFilter: "blur(12px)",
              }}
            >
              {/* Browser bar */}
              <div style={{
                background: "linear-gradient(180deg, rgba(212,148,10,0.04), transparent)",
                padding: "10px 16px",
                display: "flex", alignItems: "center", gap: 8,
                borderBottom: "1px solid var(--border)",
              }}>
                <div style={{ display: "flex", gap: 5 }}>
                  {["#ff5f57", "#febc2e", "#28c840"].map(c => (
                    <div key={c} style={{ width: 10, height: 10, borderRadius: "50%", background: c }} />
                  ))}
                </div>
                <div style={{ flex: 1, display: "flex", justifyContent: "center" }}>
                  <div style={{
                    background: "var(--bg)", borderRadius: 6, padding: "5px 16px",
                    fontSize: 10, color: "var(--text-muted)", maxWidth: 240, width: "100%",
                    textAlign: "center", display: "flex", alignItems: "center", justifyContent: "center", gap: 4,
                    border: "1px solid var(--border)",
                  }}>
                    <span style={{ fontSize: 9 }}>🔒</span>
                    <span>interview-prep-ai.com</span>
                  </div>
                </div>
              </div>

              {/* App preview content */}
              <div className="hero-preview-inner" style={{
                padding: "20px 22px", display: "grid",
                gridTemplateColumns: "1fr 220px", gap: 16,
                background: "var(--bg-warm)",
              }}>
                <div>
                  <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 16 }}>
                    <span style={{ fontSize: 13, fontWeight: 700 }}>Interview Prep AI</span>
                    <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
                      <div style={{
                        width: 28, height: 28, borderRadius: "50%",
                        background: "linear-gradient(135deg, #d4940a, #f5d06b)",
                        display: "flex", alignItems: "center", justifyContent: "center",
                        fontSize: 11, fontWeight: 700, color: "#fff",
                        boxShadow: "0 2px 6px rgba(212,148,10,0.25)",
                      }}>M</div>
                      <div>
                        <div style={{ fontSize: 11, fontWeight: 600 }}>Harsh Majawdiya</div>
                        <div style={{ fontSize: 9, color: "var(--accent)" }}>Logout</div>
                      </div>
                    </div>
                  </div>
                  <h3 style={{ fontSize: 16, fontWeight: 700, marginBottom: 3 }}>Frontend Developer</h3>
                  <p style={{ color: "var(--text-muted)", fontSize: 11, marginBottom: 10 }}>React.js, DOM, CSS Flexbox</p>
                  <div style={{ display: "flex", gap: 6, marginBottom: 14, flexWrap: "wrap" }}>
                    {["2 Years Exp", "10 Q&A", "Apr 2025"].map(tag => (
                      <span key={tag} style={{
                        background: "var(--tag-bg)", color: "var(--tag-text)",
                        padding: "3px 10px", borderRadius: "var(--radius-full)",
                        fontSize: 9, fontWeight: 500,
                      }}>{tag}</span>
                    ))}
                  </div>
                  <h4 style={{ fontSize: 10, fontWeight: 600, marginBottom: 8, color: "var(--text-muted)", letterSpacing: "0.5px", textTransform: "uppercase" }}>Interview Q & A</h4>
                  {["What is JSX? Explain its role in React.", "What is React.js and its advantages?", "Props vs state in React."].map((q, i) => (
                    <div key={i} style={{
                      display: "flex", justifyContent: "space-between", alignItems: "center",
                      padding: "10px 0", borderBottom: "1px solid var(--border)",
                    }}>
                      <div style={{ display: "flex", gap: 8, alignItems: "center" }}>
                        <span style={{
                          width: 16, height: 16, borderRadius: "50%",
                          background: i === 0 ? "var(--accent-light)" : "transparent",
                          border: `2px solid ${i === 0 ? "var(--accent)" : "var(--border)"}`,
                          display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0,
                        }}>
                          {i === 0 && <span style={{ width: 5, height: 5, borderRadius: "50%", background: "var(--accent)" }} />}
                        </span>
                        <span style={{ fontSize: 11 }}>{q}</span>
                      </div>
                      <div style={{ display: "flex", gap: 6 }}>
                        {i === 0 && (
                          <button style={{
                            background: "linear-gradient(135deg, #d4940a, #b8860b)",
                            color: "#fff", border: "none", padding: "3px 10px",
                            borderRadius: "var(--radius-full)", fontSize: 9, fontWeight: 600, cursor: "pointer",
                            boxShadow: "0 2px 6px rgba(212,148,10,0.2)",
                          }}>✦ Learn More</button>
                        )}
                        <span style={{ color: "var(--text-muted)", fontSize: 10 }}>▾</span>
                      </div>
                    </div>
                  ))}
                </div>

                {/* Side panel */}
                <div className="hero-preview-side" style={{
                  background: "var(--bg-card)", borderRadius: "var(--radius-lg)", padding: 16,
                  border: "1px solid var(--border)", boxShadow: "var(--shadow-card)",
                }}>
                  <div style={{ display: "flex", justifyContent: "space-between", marginBottom: 10 }}>
                    <h4 style={{ fontWeight: 700, fontSize: 12, lineHeight: 1.4 }}>CSS Flexbox Guide</h4>
                    <span style={{ color: "var(--text-muted)", cursor: "pointer", fontSize: 12 }}>✕</span>
                  </div>
                  <p style={{ fontSize: 10, color: "var(--text-secondary)", lineHeight: 1.7, marginBottom: 10 }}>
                    CSS Flexbox is a powerful layout model designed to make flexible and responsive layouts easy...
                  </p>
                  <p style={{ fontSize: 10, fontWeight: 600, marginBottom: 6 }}>Basic Concepts:</p>
                  <div style={{
                    background: "var(--bg-code)", borderRadius: "var(--radius-md)",
                    padding: 10, fontFamily: "var(--font-mono)", fontSize: 10, color: "#a8ff78",
                  }}>
                    .container {"{"}<br />&nbsp;&nbsp;display: flex;<br />{"}"}
                  </div>
                </div>
              </div>
            </div>
          </motion.div>
        </div>
      </section>

      {/* ===== Golden Divider ===== */}
      <div className="golden-divider" style={{ maxWidth: 1100, margin: "0 auto" }} />

      {/* ===== Features Section ===== */}
      <section
        id="features"
        ref={featuresRef}
        style={{
          padding: "100px 40px",
          background: "var(--bg-section-alt)",
          position: "relative",
        }}
      >
        <GeoPattern />
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={featuresInView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.5 }}
          style={{ textAlign: "center", marginBottom: 64, position: "relative", zIndex: 1 }}
        >
          <div className="premium-badge" style={{ marginBottom: 16 }}>
            <span>✦</span> WHY CHOOSE US
          </div>
          <h2 style={{
            fontFamily: "var(--font-serif)", fontSize: "clamp(30px, 3.5vw, 48px)",
            letterSpacing: "-1px", marginBottom: 16,
          }}>
            Features That Make You{" "}
            <span className="gradient-text" style={{ fontStyle: "italic" }}>Shine</span>
          </h2>
          <p style={{
            fontSize: 16, color: "var(--text-secondary)", maxWidth: 550, margin: "0 auto", lineHeight: 1.7,
          }}>
            Every tool you need for comprehensive interview preparation, powered by advanced AI.
          </p>
        </motion.div>

        <div style={{
          display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: 20,
          maxWidth: 1100, margin: "0 auto", position: "relative", zIndex: 1,
        }}>
          {features.map((f, i) => (
            <motion.div
              key={i}
              initial={{ opacity: 0, y: 30 }}
              animate={featuresInView ? { opacity: 1, y: 0 } : {}}
              transition={{ duration: 0.5, delay: i * 0.1 }}
              whileHover={{ y: -8, boxShadow: "var(--shadow-card-hover)" }}
              className="glass-card"
              style={{
                borderRadius: "var(--radius-xl)", padding: 32, textAlign: "left",
                cursor: "default",
                gridColumn: i >= 3 ? "span 1" : undefined,
                borderTop: `3px solid ${f.color}`,
                position: "relative", overflow: "hidden",
              }}
            >
              {/* Glow effect on hover */}
              <div style={{
                position: "absolute", top: 0, left: 0, right: 0, height: "3px",
                background: f.gradient, filter: "blur(8px)", opacity: 0.5,
              }} />
              {/* Icon */}
              <div style={{
                width: 52, height: 52, borderRadius: "var(--radius-md)",
                background: `${f.color}12`, display: "flex", alignItems: "center",
                justifyContent: "center", fontSize: 24, marginBottom: 20,
                border: `1px solid ${f.color}20`,
              }}>
                {f.icon}
              </div>
              {/* Step badge */}
              <div style={{
                fontSize: 11, fontWeight: 700, color: f.color,
                letterSpacing: 1.5, textTransform: "uppercase", marginBottom: 10,
              }}>
                {String(i + 1).padStart(2, "0")}
              </div>
              <h3 style={{ fontSize: 17, fontWeight: 700, marginBottom: 12, letterSpacing: "-0.3px" }}>{f.title}</h3>
              <p style={{ fontSize: 14, color: "var(--text-secondary)", lineHeight: 1.7 }}>{f.desc}</p>
            </motion.div>
          ))}
        </div>
      </section>

      {/* ===== Golden Divider ===== */}
      <div className="golden-divider" style={{ maxWidth: 1100, margin: "0 auto" }} />

      {/* ===== How It Works Section ===== */}
      <section
        id="how-it-works"
        ref={howRef}
        style={{
          padding: "100px 40px",
          position: "relative",
        }}
      >
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={howInView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.5 }}
          style={{ textAlign: "center", marginBottom: 64 }}
        >
          <div className="premium-badge" style={{ marginBottom: 16 }}>
            <span>✦</span> SIMPLE PROCESS
          </div>
          <h2 style={{
            fontFamily: "var(--font-serif)", fontSize: "clamp(30px, 3.5vw, 48px)",
            letterSpacing: "-1px", marginBottom: 16,
          }}>
            How It{" "}
            <span className="gradient-text" style={{ fontStyle: "italic" }}>Works</span>
          </h2>
          <p style={{
            fontSize: 16, color: "var(--text-secondary)", maxWidth: 500, margin: "0 auto", lineHeight: 1.7,
          }}>
            Four simple steps to transform your interview preparation journey.
          </p>
        </motion.div>

        <div style={{
          maxWidth: 900, margin: "0 auto",
          display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: 24,
          position: "relative",
        }}>
          {/* Connecting line */}
          <div style={{
            position: "absolute", top: 44, left: "12%", right: "12%", height: 2,
            background: "linear-gradient(90deg, transparent, var(--border-golden), var(--gold-2), var(--border-golden), transparent)",
            zIndex: 0,
          }} />

          {steps.map((step, i) => (
            <motion.div
              key={i}
              initial={{ opacity: 0, y: 30 }}
              animate={howInView ? { opacity: 1, y: 0 } : {}}
              transition={{ duration: 0.5, delay: i * 0.15 }}
              style={{
                textAlign: "center", position: "relative", zIndex: 1,
              }}
            >
              {/* Step circle */}
              <motion.div
                whileHover={{ scale: 1.1, boxShadow: "0 8px 30px rgba(212,148,10,0.3)" }}
                style={{
                  width: 88, height: 88, borderRadius: "50%",
                  background: "var(--bg-card)",
                  border: "2px solid var(--border-golden)",
                  display: "flex", alignItems: "center", justifyContent: "center",
                  fontSize: 36, margin: "0 auto 20px",
                  boxShadow: "var(--shadow-golden)",
                  cursor: "default",
                  position: "relative",
                  backdropFilter: "blur(10px)",
                }}
              >
                {step.icon}
                {/* Step number */}
                <div style={{
                  position: "absolute", bottom: -4, right: -4,
                  width: 24, height: 24, borderRadius: "50%",
                  background: "linear-gradient(135deg, #d4940a, #b8860b)",
                  color: "#fff", fontSize: 10, fontWeight: 700,
                  display: "flex", alignItems: "center", justifyContent: "center",
                  boxShadow: "0 2px 6px rgba(212,148,10,0.3)",
                }}>
                  {step.num}
                </div>
              </motion.div>
              <h3 style={{ fontSize: 16, fontWeight: 700, marginBottom: 8, letterSpacing: "-0.2px" }}>{step.title}</h3>
              <p style={{ fontSize: 13, color: "var(--text-secondary)", lineHeight: 1.65 }}>{step.desc}</p>
            </motion.div>
          ))}
        </div>
      </section>



      {/* ===== CTA Section ===== */}
      <section style={{
        padding: "100px 40px", textAlign: "center",
        position: "relative", overflow: "hidden",
      }}>
        {/* Decorative background */}
        <div style={{
          position: "absolute", inset: 0,
          background: "radial-gradient(ellipse 80% 50% at 50% 50%, rgba(212,148,10,0.06) 0%, transparent 60%)",
          pointerEvents: "none",
        }} />

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          style={{ maxWidth: 640, margin: "0 auto", position: "relative", zIndex: 1 }}
        >
          <div className="premium-badge" style={{ marginBottom: 20 }}>
            <span>🚀</span> START NOW
          </div>
          <h2 style={{
            fontFamily: "var(--font-serif)", fontSize: "clamp(30px, 4vw, 48px)",
            marginBottom: 18, letterSpacing: "-1px",
          }}>
            Ready to Ace Your{" "}
            <span className="gradient-text" style={{ fontStyle: "italic" }}>Interview?</span>
          </h2>
          <p style={{
            fontSize: 17, color: "var(--text-secondary)", lineHeight: 1.75, marginBottom: 36,
          }}>
            Join hundreds of developers who have boosted their confidence and landed their dream roles with AI-powered preparation.
          </p>
          <motion.button
            onClick={() => setModal("signup")}
            whileHover={{ y: -3, boxShadow: "0 12px 40px rgba(212,148,10,0.45)" }}
            whileTap={{ scale: 0.98 }}
            className="golden-shine"
            style={{
              background: "linear-gradient(135deg, #d4940a, #b8860b)",
              color: "#fff", border: "none", padding: "18px 48px",
              borderRadius: "var(--radius-full)", fontSize: 16, fontWeight: 600,
              cursor: "pointer", fontFamily: "inherit",
              boxShadow: "0 8px 30px rgba(212,148,10,0.35)",
              display: "inline-flex", alignItems: "center", gap: 10,
              letterSpacing: "0.3px",
            }}
          >
            Start Preparing Now <span style={{ fontSize: 18 }}>→</span>
          </motion.button>
        </motion.div>
      </section>

      {/* ===== Golden Divider ===== */}
      <div className="golden-divider" />

      {/* ===== Footer ===== */}
      <footer style={{
        padding: "48px 60px 32px",
        background: "linear-gradient(180deg, var(--bg) 0%, rgba(212,148,10,0.03) 100%)",
      }}>
        <div style={{ maxWidth: 1100, margin: "0 auto" }}>
          {/* Top row: logo + links */}
          <div style={{
            display: "flex", justifyContent: "space-between", alignItems: "center",
            flexWrap: "wrap", gap: 20, marginBottom: 28,
          }}>
            <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
              <div style={{
                width: 30, height: 30, borderRadius: 8,
                background: "linear-gradient(135deg, #d4940a, #f5d06b)",
                display: "flex", alignItems: "center", justifyContent: "center",
                fontSize: 14, color: "#fff", fontWeight: 700,
                boxShadow: "0 2px 8px rgba(212,148,10,0.2)",
              }}>✦</div>
              <span style={{ fontSize: 15, fontWeight: 700 }}>
                Interview Prep <span style={{ color: "var(--accent)" }}>AI</span>
              </span>
            </div>
            <div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}>
              {footerLinks.map(link => (
                <button
                  key={link.name}
                  onClick={() => setActiveFooterLink(activeFooterLink === link.name ? null : link.name)}
                  style={{
                    display: "flex", alignItems: "center", gap: 6,
                    fontSize: 13, fontWeight: 600, cursor: "pointer",
                    fontFamily: "inherit",
                    padding: "8px 16px", borderRadius: "var(--radius-full)",
                    transition: "all 0.25s ease",
                    background: activeFooterLink === link.name
                      ? "linear-gradient(135deg, rgba(212,148,10,0.12), rgba(245,208,107,0.15))"
                      : "transparent",
                    color: activeFooterLink === link.name ? "var(--accent)" : "var(--text-muted)",
                    border: activeFooterLink === link.name
                      ? "1px solid rgba(212,148,10,0.25)"
                      : "1px solid transparent",
                  }}
                  onMouseEnter={e => {
                    if (activeFooterLink !== link.name) {
                      e.currentTarget.style.color = "var(--text)";
                      e.currentTarget.style.background = "rgba(212,148,10,0.04)";
                    }
                  }}
                  onMouseLeave={e => {
                    if (activeFooterLink !== link.name) {
                      e.currentTarget.style.color = "var(--text-muted)";
                      e.currentTarget.style.background = "transparent";
                    }
                  }}
                >
                  <span style={{ fontSize: 12 }}>{link.icon}</span>
                  {link.name}
                  <span style={{
                    fontSize: 10, transition: "transform 0.3s ease",
                    transform: activeFooterLink === link.name ? "rotate(180deg)" : "rotate(0deg)",
                    marginLeft: 2,
                  }}>▼</span>
                </button>
              ))}
            </div>
          </div>

          {/* Expandable description panel */}
          <AnimatePresence mode="wait">
            {activeFooterLink && (
              <motion.div
                key={activeFooterLink}
                initial={{ opacity: 0, height: 0, marginBottom: 0 }}
                animate={{ opacity: 1, height: "auto", marginBottom: 24 }}
                exit={{ opacity: 0, height: 0, marginBottom: 0 }}
                transition={{ duration: 0.35, ease: [0.22, 1, 0.36, 1] }}
                style={{ overflow: "hidden" }}
              >
                <div
                  className="glass-card"
                  style={{
                    borderRadius: "var(--radius-xl)", padding: "24px 32px",
                    borderLeft: "3px solid var(--accent)",
                    display: "flex", alignItems: "flex-start", gap: 16,
                  }}
                >
                  <div style={{
                    width: 40, height: 40, borderRadius: "var(--radius-md)",
                    background: "linear-gradient(135deg, rgba(212,148,10,0.1), rgba(245,208,107,0.15))",
                    border: "1px solid rgba(212,148,10,0.15)",
                    display: "flex", alignItems: "center", justifyContent: "center",
                    fontSize: 18, flexShrink: 0,
                  }}>
                    {footerLinks.find(l => l.name === activeFooterLink)?.icon}
                  </div>
                  <div>
                    <h4 style={{
                      fontSize: 15, fontWeight: 700, marginBottom: 8,
                      color: "var(--text)", letterSpacing: "-0.3px",
                    }}>
                      {activeFooterLink}
                    </h4>
                    <p style={{
                      fontSize: 14, color: "var(--text-secondary)",
                      lineHeight: 1.75, margin: 0,
                    }}>
                      {footerLinks.find(l => l.name === activeFooterLink)?.desc}
                    </p>
                  </div>
                </div>
              </motion.div>
            )}
          </AnimatePresence>

        </div>
      </footer>

      {/* ===== Scroll to Top ===== */}
      <motion.button
        initial={{ opacity: 0, scale: 0.8 }}
        animate={scrolled ? { opacity: 1, scale: 1 } : { opacity: 0, scale: 0.8 }}
        whileHover={{ y: -3, boxShadow: "0 8px 25px rgba(212,148,10,0.3)" }}
        onClick={() => window.scrollTo({ top: 0, behavior: "smooth" })}
        style={{
          position: "fixed", bottom: 32, right: 32,
          width: 48, height: 48, borderRadius: "50%",
          background: "linear-gradient(135deg, #d4940a, #f5d06b)",
          border: "none",
          boxShadow: "0 4px 15px rgba(212,148,10,0.3)",
          cursor: "pointer",
          display: "flex", alignItems: "center", justifyContent: "center",
          fontSize: 18, zIndex: 90, color: "#fff", fontWeight: 700,
        }}
      >
        ↑
      </motion.button>

      {/* ===== Auth Modals ===== */}
      {modal === "login" && <LoginModal onClose={() => setModal(null)} onSwitchToSignup={() => setModal("signup")} />}
      {modal === "signup" && <SignupModal onClose={() => setModal(null)} onSwitchToLogin={() => setModal("login")} />}
    </motion.div>
  );
};

export default Landing;